name: daily_solve

on:
  schedule:
    - cron: '0 5 * * *'
    
  workflow_dispatch:

jobs:
  daily_solve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Solve today's puzzle
        run: ./daily_puzzle.py -a
      - uses: EndBug/add-and-commit@v7
        with:
          message: "Solve daily puzzle"
          add: "['daily_puzzle.db', 'solutions.txt']"
